# Generated by Django 3.2.5 on 2021-07-08 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время не может быть меньше 1 минуты'), django.core.validators.MaxValueValidator(1000, message='Слишком долго, укажите время в минутах')], verbose_name='Время приготовления, мин'),
        ),
    ]
