# Generated by Django 3.2.5 on 2021-07-10 04:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='api.ingredient'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000, message='Слишком много, проверьте единицы измерения')], verbose_name='Количество'),
        ),
    ]
