# Generated by Django 3.2.5 on 2021-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210720_2032'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='user_and_favorite_uniq_together',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_and_recipe_uniq_together'),
        ),
    ]
