# Generated by Django 3.2.5 on 2021-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210721_1941'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='user_and_purchase_uniq_together',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_and_purchase_uniq_together'),
        ),
    ]
