# Generated by Django 3.2.5 on 2021-07-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210725_2343'),
    ]

    database_operations = [migrations.AlterModelTable('Subscription', 'users_subscription')]

    state_operations = [migrations.DeleteModel('Subscription')]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
