# Generated by Django 3.2.5 on 2021-07-29 17:47

import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210726_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767, message='Слишком много, проверьте единицы измерения'), django.core.validators.MinValueValidator(1, message='Слишком мало, проверьте единицы измерения')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[800, 800], upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
