version: '3.3'
services:
  db:
    image: postgres:12
    container_name: foodgram_db
    restart: always
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db
  backend:
    build: .
    container_name: foodgram_backend
    restart: always
    command: gunicorn project.wsgi --bind 0.0.0.0:8002
    volumes:
      - static_value:/foodgram/static/
      - media_value:/foodgram/media/
    depends_on:
      - frontend
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    container_name: foodgram_nginx
    restart: always
    ports:
      - '8002:8002'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build/:/usr/share/nginx/html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend

volumes:
  foodgram_db:
  static_value:
  media_value:
