version: '3.3'
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: hlystovea/foodgram_back:latest
    restart: always
    command: gunicorn project.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: hlystovea/foodgram_front:latest
    volumes:
      - ./build:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
