# Generated by Django 3.2.5 on 2021-07-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('users', '0002_auto_20210726_2149'),
    ]

    operations = [
    ]
