# Generated by Django 3.2.5 on 2021-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0001_initial_0002_auto_20210726_2149'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='sub_user_and_author_uniq_together'),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table=None,
        ),
    ]
